version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DB_TYPE: 'POSTGRES'
  DB_URL: postgres://postgres:postgres@postgres/swift-study
  
services:
  swift-study:
    image: ghcr.io/dracks/swift-language-study:nightly
    build:
      context: .
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
  postgres:
    restart: always
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: swift-study
    ports:
      - 5432:5432